### ISSUE TITLE
Pypi has not be published in a while

### ISSUE THREAD

**Issue by spapin** [Alidron/spyrk#10]
@AxelVoitier please let me know if this is the correct way to surface this: The spyrk version available from pypi is years old now.

Any plans to release a new version? The current one breaks because the fix from the pull request https://github.com/Alidron/spyrk/pull/6 is missing

**Comment by AxelVoitier** [comment]
Yes! I though about it yesterday :).
I will have a look at it.

**Comment by AxelVoitier** [comment]
Done o/

https://pypi.python.org/pypi/spyrk/0.0.4
